'use strict';let b=document.getElementById("canvas"),c=b.getContext("2d"),g=[],h=false,k=false;const p=function m(a,d,f,l="images/",e=".svg"){let n={};for(let f of a)for(let a of d){n[f+a]=new Image;n[f+a].src=l+f+a+e}for(let a of f){n[a]=new Image;n[a].src=l+a+e}return n}(["a",2,3,4,5,6,7,8,9,10,"j","q","k"],["h","d","c","s"],["back","empty","outline"]);function r(){c.clearRect(0,0,c.canvas.width,c.canvas.height)}function t(a,d,f,l=.5){c.drawImage(a,d,f,a.naturalWidth*l,a.naturalHeight*l)}
function u(){r();g.slice().reverse().forEach(function(a){a.A()})}
function v(a){this.direction=0;this.b=false;this.size=.5;this.D=a[0];this.F=a[1];this.valueOf=function(){return this.D+this.F};this.y=this.x=0;this.g=p[a];this.outline=false;this.A=function(){if(this.direction){c.save();c.translate(this.x,this.y);c.rotate(this.direction);t(this.b?p.back:this.g,0,0,this.size);if(this.outline){this.outline==="w"?t(p.outline,22.5,0,this.size):this.outline==="x"&&t(p.outline,2,2,this.size);this.outline=false}c.restore()}else{t(this.b?p.back:this.g,this.x,this.y,
this.size);if(this.outline){this.outline==="w"?t(p.outline,this.x+22.5,this.y,this.size):this.outline==="x"&&t(p.outline,this.x+2,this.y+2,this.size);this.outline=false}}};Object.defineProperties(this,{width:{get:function(){return this.g.naturalWidth*this.size}},height:{get:function(){return this.g.naturalHeight*this.size}},c:{get:function(){switch(this.direction){case 0:return this.x+this.width;case Math.PI*.5:return this.x-this.height;case Math.PI:return this.x-this.width;case Math.PI*1.5:return this.x+
this.height}}},f:{get:function(){switch(this.direction){case 0:return this.y+this.height;case Math.PI*.5:return this.y+this.width;case Math.PI:return this.y-this.height;case Math.PI*1.5:return this.y-this.width}}}});this.s=function(a,f){switch(this.direction){case 0:return a>=this.x&&a<=this.c&&f>=this.y&&f<=this.f;case Math.PI*.5:return a<=this.x&&a>=this.c&&f>=this.y&&f<=this.f;case Math.PI:return a<=this.x&&a>=this.c&&f<=this.y&&f>=this.f;case Math.PI*1.5:return a>=this.x&&a<=this.c&&f<=this.y&&
f>=this.f}}}
class w extends Array{constructor(...a){super();Object.defineProperties(this,{width:{get:function(){return this[0]?(this.length-1)*45*this[0].size+this[0].g.naturalWidth*this[0].size:void 0}},height:{get:function(){return this[0]?this[0].g.naturalHeight*this[0].size:void 0}},c:{get:function(){switch(this.direction){case 0:return this.x+this.width;case Math.PI*.5:return this.x-this.height;case Math.PI:return this.x-this.width;case Math.PI*1.5:return this.x+this.height}}},f:{get:function(){switch(this.direction){case 0:return this.y+this.height;
case Math.PI*.5:return this.y+this.width;case Math.PI:return this.y-this.height;case Math.PI*1.5:return this.y-this.width}}},x:{get:function(){return this.v},set:function(a){if(this[0])this[0].x=a;this.v=a}},y:{get:function(){return this.w},set:function(a){if(this[0])this[0].y=a;this.w=a}}});this.b=false;this.direction=0;this.l=this.i=false;if(typeof a[0]==="number"){this.x=a[0];this.y=a[1];this.push(...a.splice(2))}else{this.y=this.x=0;this.push(...a)}}A(){if(this.direction){c.save();c.translate(this.x,
this.y);c.rotate(this.direction);this.forEach(function(a,d){t(this.b?p.back:a.g,d*45*this[0].size,0,this[0].size);if(this.i===d||h.u&&!h.h&&a===h.u){t(p.outline,d*45*this[0].size,0,this[0].size);if(this.i!==false)this.i=false}},this);if(this.l){t(p.outline,this.length*45*this[0].size,0,this[0].size);this.l=false}c.restore()}else{this.forEach(function(a,d){t(this.b?p.back:a.g,this.x+d*45*this[0].size,this.y,this[0].size);if(this.i===d||h.u&&!h.h&&a===h.u){t(p.outline,this.x+d*45*this[0].size,this.y,
this[0].size);if(this.i!==false)this.i=false}},this);if(this.l){t(p.outline,this.x+this.length*45*this[0].size,this.y,this[0].size);this.l=false}}}s(a,d){switch(this.direction){case 0:return a>=this.x&&a<=this.c&&d>=this.y&&d<=this.f;case Math.PI*.5:return a<=this.x&&a>=this.c&&d>=this.y&&d<=this.f;case Math.PI:return a<=this.x&&a>=this.c&&d<=this.y&&d>=this.f;case Math.PI*1.5:return a>=this.x&&a<=this.c&&d<=this.y&&d>=this.f}}o(a,d,f=false,l=true){let e;switch(this.direction){case 0:e=Math.floor((a-
this.x)/22.5);break;case Math.PI*.5:e=Math.floor((d-this.y)/22.5);break;case Math.PI:e=Math.floor((this.x-a)/22.5);break;case Math.PI*1.5:e=Math.floor((this.y-d)/22.5)}return f?l?e<this.length?e:this.length-1:e:this[e<this.length?e:this.length-1]}}
b.addEventListener("mousedown",function(a){if(!h){let d=a.clientX,f=a.clientY,l=g.findIndex((a)=>a.s(d,f)),e=g[l];if(e){let q=e.constructor.name.toLowerCase();if(a.button===0){if(e.b){q!=="w"&&q!=="x"||e.reverse();e.b=false}}else if(a.button===2&&!e.b){q!=="w"&&q!=="x"||e.reverse();e.b=true}h={type:q,object:e,x:d,y:f,e:a,timeStamp:a.timeStamp,h:a.timeStamp-k.timeStamp<500&&e===k.object,u:e.constructor.name.toLowerCase()==="w"?e.o(d,f):void 0,C:e.constructor.name.toLowerCase()===
"w"?e.indexOf(e.o(d,f)):void 0,m:false,index:l};console.log(h);g[0]!==e&&g.unshift(g.splice(g.indexOf(e),1)[0]);u()}}});
b.addEventListener("mousemove",function(a){if(h){h.x=a.clientX;h.y=a.clientY;if(!h.m){if(h.type!=="v")if(h.type==="w")if(h.h)console.log("first time double clicked stack");else{g.unshift(h.object.splice(h.C,1)[0]);var d=h.C;g[0].b=g[1].b;g[0].direction=g[1].direction;if(g[1].length===1){g[1][0].b=g[1].b;g[1][0].direction=g[1].direction;g[1][0].x=g[1].x;g[1][0].y=g[1].y;g.splice(1,1,g[1][0])}h={type:"v",object:g[0],x:a.clientX,y:a.clientY,e:a,timeStamp:a.timeStamp,h:false,m:true,index:0};
switch(g[0].direction){case 0:g[0].x=g[1].x+d*22.5;g[0].y=g[1].y;break;case Math.PI*.5:g[0].x=g[1].x;g[0].y=g[1].y+d*22.5;break;case Math.PI:g[0].x=g[1].x-d*22.5;g[0].y=g[1].y;break;case Math.PI*1.5:g[0].x=g[1].x;g[0].y=g[1].y-d*22.5}g[0].direction=g[1].direction}else if(h.type==="x")if(h.h)console.log("first double clicked pile");else{g.unshift(h.object.shift());g[0].b=g[1].b;g[0].direction=g[1].direction;if(g[1].length===1){g[1][0].b=g[1].b;g[1][0].direction=g[1].direction;g[1][0].x=g[1].x-2;
g[1][0].y=g[1].y-2;g.splice(1,1,g[1][0])}h={type:"v",object:g[0],x:a.clientX,y:a.clientY,e:a,timeStamp:a.timeStamp,h:false,m:true,index:0}}h.m=true}if(h.type==="v"){g[0].x=g[0].x+a.movementX;g[0].y=g[0].y+a.movementY}else if(h.type==="w")if(h.h){g[0].x=g[0].x+a.movementX;g[0].y=g[0].y+a.movementY}else console.log("single clicked stack");else if(h.type==="x")if(h.h){g[0].x=g[0].x+a.movementX;g[0].y=g[0].y+a.movementY}else console.log("single clicked pile");else console.log("object type not recognized in mousemove",
h);if(h.type==="v"){h.B=g.findIndex((d)=>d!==h.object&&d.s(a.clientX,a.clientY));h.a=g[h.B];if(h.a)if(h.a.constructor.name.toLowerCase()==="x")h.a.j=true;else if(h.a.constructor.name.toLowerCase()==="w"){d=h.a.o(a.clientX,a.clientY,true,false);if(d>h.a.length){h.a.l=true;h.a.i=h.a.length}else h.a.i=d}else if(h.a.constructor.name.toLowerCase()==="v"){d=h.object.x-h.a.x;if(h.object.y-h.a.y<.5*h.a.height)if(22.5<=d&&d<45)h.a.outline="w";else if(-22.5<=d&&d<22.5)h.a.outline="x"}}u()}});
b.addEventListener("mouseup",function(){if(h){k=h;if(h.a)if(h.a.constructor.name.toLowerCase()==="x"){h.a.unshift(g[0]);g.splice(0,1)}else if(h.a.constructor.name.toLowerCase()==="w"){var a=h.a.o(h.x,h.y,true,false);h.a.splice(a>h.a.length?h.a.length:a,0,g[0]);if(h.a.l){h.a.i=false;h.a.l=false}g.splice(0,1);u()}else if(h.a.constructor.name.toLowerCase()==="v"){a=h.object.x-h.a.x;if(h.object.y-h.a.y<.5*h.a.height)if(22.5<=a&&a<45){g.splice(0,1,new w(h.a.x,h.a.y,g.splice(h.B,1)[0],h.object));
g[0].b=h.a.b;g[0].direction=h.a.direction}else if(-22.5<=a&&a<22.5){g.splice(0,1,new x(h.a.x,h.a.y,g.splice(h.B,1)[0],h.object));g[0].b=h.a.b;g[0].direction=h.a.direction}}h=false}console.log(false);u()});window.addEventListener("keypress",function(a){switch(a.key){case "d":console.log(h);break;case "a":console.log(g);break;default:console.log(a)}});b.oncontextmenu=()=>false;p.empty.addEventListener("load",function(){u()},{once:true});
class x extends Array{constructor(...a){super();Object.defineProperties(this,{width:{get:function(){return this[0]?this[0].g.naturalWidth*this[0].size:void 0}},height:{get:function(){return this[0]?this[0].g.naturalHeight*this[0].size:void 0}},c:{get:function(){switch(this.direction){case 0:return this.x+this.width;case Math.PI*.5:return this.x-this.height;case Math.PI:return this.x-this.width;case Math.PI*1.5:return this.x+this.height}}},f:{get:function(){switch(this.direction){case 0:return this.y+
this.height;case Math.PI*.5:return this.y+this.width;case Math.PI:return this.y-this.height;case Math.PI*1.5:return this.y-this.width}}},x:{get:function(){return this.v},set:function(a){if(this[0])this[0].x=a;this.v=a}},y:{get:function(){return this.w},set:function(a){if(this[0])this[0].y=a;this.w=a}}});this.b=false;this.direction=0;this.j=false;if(typeof a[0]==="number"){this.x=a[0];this.y=a[1];this.push(...a.splice(2))}else{this.y=this.x=0;this.push(...a)}}A(){if(this[0]){[this[0].x,this[0].y,this[0].size]=
[this.x,this.y,.5];if(this.direction){c.save();c.translate(this.x,this.y);c.rotate(this.direction);let a;for(a of Array.from(Array(this.length>5?4:this.length-1).keys()).reverse())t(p.empty,this.x-(a+1)*2,this.y-(a+1)*2);t(this.b?p.back:this[0].g,0,0,this[0].size);if(this.j||h.object===this&&!h.h){t(p.outline,this.x,this.y);if(this.j)this.j=false}c.restore()}else{for(let a of Array.from(Array(this.length>5?4:this.length-1).keys()).reverse())t(p.empty,this.x-(a+1)*2,this.y-(a+1)*2);t(this.b?p.back:
this[0].g,this.x,this.y,this[0].size);if(this.j||h.object===this&&!h.h){t(p.outline,this.x,this.y);if(this.j)this.j=false}}}}s(a,d){switch(this.direction){case 0:return a>=this.x&&a<=this.c&&d>=this.y&&d<=this.f;case Math.PI*.5:return a<=this.x&&a>=this.c&&d>=this.y&&d<=this.f;case Math.PI:return a<=this.x&&a>=this.c&&d<=this.y&&d>=this.f;case Math.PI*1.5:return a>=this.x&&a<=this.c&&d<=this.y&&d>=this.f}}}let y=[];
for(let a of["a",2,3,4,5,6,7,8,9,10,"j","q","k"])for(let d of["h","d","c","s"])y.push(new v(a+d));let z=new x(...y);z.x=(window.innerWidth-111.5)/2;z.y=(window.innerHeight-162)/2;g.push(z);
